In [ ]:
# default_exp pytorch_weight_decay

# Pytorch weight decay

> Pytorch weight decay or L2 penalty

In [ ]:
#hide
from nbdev.showdoc import *

In [ ]:
import numpy as np
import torch

In [ ]:
np.random.seed(123)
np.set_printoptions(8, suppress=True)

### Without weight decay

In [ ]:
x_np = np.random.random((3,4)).astype(np.double)
w_np = np.random.random((4,5)).astype(np.double)
x_tensor = torch.tensor(x_np, requires_grad=True)
w_tensor = torch.tensor(w_np, requires_grad=True)

In [ ]:
print("Original weights: \n", w_tensor)

lr  = 0.1
sgd = torch.optim.SGD([w_tensor], lr=lr, weight_decay=0)

y_tensor = torch.matmul(x_tensor, w_tensor)
loss = y_tensor.sum()

sgd.zero_grad()
loss.backward()
sgd.step()

w_grad = w_tensor.grad

print("Zero weight decay: \n", w_tensor)

Original weights: 
 tensor([[ 0.1507,  0.1129,  0.2012, -0.5800, -0.6269],
        [-0.7232, -0.4622, -0.4373, -0.2994, -0.7394],
        [-0.4603,  0.1499, -0.1938,  0.1462, -0.6543],
        [ 0.1149,  0.4953,  0.1455, -0.2306,  0.2811]], dtype=torch.float64,
       requires_grad=True)
Zero weight decay: 
 tensor([[-0.0264, -0.0643,  0.0241, -0.7572, -0.8040],
        [-0.9386, -0.6776, -0.6527, -0.5148, -0.9548],
        [-0.6258, -0.0155, -0.3592, -0.0192, -0.8197],
        [ 0.0058,  0.3861,  0.0364, -0.3397,  0.1719]], dtype=torch.float64,
       requires_grad=True)


### With weight decay

In [ ]:
w_tensor = torch.tensor(w_np, requires_grad=True)
print("Reset original weights: \n", w_tensor)

sgd = torch.optim.SGD([w_tensor], lr=lr, weight_decay=1)

y_tensor = torch.matmul(x_tensor, w_tensor)
loss = y_tensor.sum()

sgd.zero_grad()
loss.backward()
sgd.step()

w_grad = w_tensor.grad

print("One weight decay: \n", w_tensor)

Reset original weights: 
 tensor([[0.8594, 0.8215, 0.9099, 0.1286, 0.0818],
        [0.1384, 0.3994, 0.4243, 0.5622, 0.1222],
        [0.2014, 0.8116, 0.4680, 0.8079, 0.0074],
        [0.5516, 0.9319, 0.5822, 0.2061, 0.7178]], dtype=torch.float64,
       requires_grad=True)
One weight decay: 
 tensor([[ 0.5963,  0.5622,  0.6417, -0.0614, -0.1036],
        [-0.0908,  0.1440,  0.1665,  0.2906, -0.1054],
        [ 0.0158,  0.5650,  0.2558,  0.5617, -0.1588],
        [ 0.3873,  0.7296,  0.4148,  0.0763,  0.5368]], dtype=torch.float64,
       requires_grad=True)
